# Welcome + name
print("Hello! Welcome to Abby's awesome mad lib, ABB LIB!!!")
playername = input("What is your name? Please type here and press enter when you're done. ")
print(f"\nWelcome to ABB LIB, {playername}! I hope you enjoy your story!")

# Enter words
print("To start, please write out some words.").strip()
name = input("Please type a NAME here and press enter when you're done. ").strip().title()
city = input("Please type a PLACE here and press enter when you're done. ").strip().title()
number = input("Please type a NUMBER here and press enter when you're done. ").strip()
object1 = input("Please type an OBJECT here and press enter when you're done. ").strip()
food = input("Please type a FOOD here and press enter when you're done. ").strip()
adjective = input("Please type an ADJECTIVE here and press enter when you're done. ").strip()
verb = input("Please type a VERB here and press enter when you're done. ").strip()
verb2 = input("Please type a VERB here and press enter when you're done. ").strip()
place = input("Please type a PLACE here and press enter when you're done. ").strip().title()
emotion = input("Please type an EMOTION here and press enter when you're done. ").strip()
action = input("Please type an ACTION here and press enter when you're done. ").strip()
colour = input("Please type a COLOUR here and press enter when you're done. ").strip()
action2 = input("Please type an ACTION here and press enter when you're done. ").strip()
adjective2 = input("Please type an ADJECTIVE here and press enter when you're done. ").strip()

# Write mad lib
print(f"\nI, {playername}, decided to go on a vacation to {city} with my #1 bestest friend, {name}.")
print("We desperately needed a break from this place.")
print(f"We got to the airport {number} hours early. The sky was a disgusting {colour}.")
print(f"When we went through security, I got stopped because I forgot to take granny's {object1} out of my pocket. Whoops!")
print(f"We got some delicious {food} for the flight and finally arrived at the gate. Man, I really love to eat {food}.")
print(f"Once we boarded the plane, I was unfortunately sitting next to a very {adjective} man. He smelled faintly of {emotion}ness.")
print(f"He spent the entire flight {verb} and talking about his weird job {verb2}.")
print(f"My bestie, {name}, was nowhere to be found. She probably bought first class tickets without telling me.")
print(f"I thought to myself, ARRRRRRRRRRRGGG shiver me timbers, {name}, when I catch you..........")
print(f"Then, I was brutally brought back to the present when the guy beside me {action2}.")
print(f"Whenever I tried to sleep, he would step around me to go to the {place}.")
print(f"He went more times than {number} people have fingers and toes.")
print(f"I was so {emotion}. Since I couldn't sleep, I decided to spend my time going {action} and {action2} instead.")
print(f"Finally, we arrived in {city}. All in all, the flight was {adjective2}!")

# Thanks for playing
print(f"\nThanks for playing, {playername}!")